### ISSUE TITLE
Suggestions on how to introduce error reading and use of help

### ISSUE THREAD

**Issue by BillMills** [swcarpentry/python-novice-gapminder#22] opened 2016-02-10 17:20 UTC
I might be getting a bit ahead of the game here, but I'm keen to see how we actually introduce errors and help. It's easy to forget, but most docs are utterly inscrutable for beginners; pointing them at the help and telling them to solve a problem with it tends to be an exercise in despair. I do agree with keeping this in there - but close guidance will be necessary.

**Comment by choldgraf** [comment] 2016-02-10 17:48
I agree with @BillMills, though I still think that you have to tell people about docstrings etc. IME when people are coding on their own and have a problem, they get really unhappy if there doesn't seem to be any next action to take to solve the problem. Then when you tell them about these things called "docstrings" they usually have this "well why the hell didn't you tell me that before" response :P 

Even if the docstrings ultimately don't help you, I think that their existence has a comforting effect on people because they feel like they can get closer to a solution (even if it's a poorly written and convoluted one)

**Comment by davis68** [comment] 2016-02-10 18:29
Is there a "softened" version of the Python docs we can link people to when introducing new functions and methods?  The main docs are indeed inscrutable.

**Comment by gvwilson** [comment] 2016-02-10 18:30
Nope.

**Comment by BillMills** [comment] 2016-02-10 19:39
That's ok - when I teach this material, 'close guidance' for error messages ==

 - Look at the first error and only the first error
 - Look at the last line and only the last line of the error (*advanced students*: find the line number of the problem in the error body, too).
 - Try and guess what that last line means from semantics.
 - Remind them that this is hard and it's ok if it looks like gibberish (because it mostly is).

You can do other stuff like guiding them through googling errors and finding things on stack, but whether I do this depends on how frazzled the student looks by this point. There are certainly other good strategies, too - the point is to cut the great glittering edifice of tech jargon down to something bite-sized for a beginner, and making sure they understand that they are not falling short of expectations by not being able to understand the docs. Without this guidance, students often feel bad that they aren't able to parse the docs, and feel doubly trapped since the implication is that they then can't help themselves if they run into problems.

(also, @choldgraf: +1 to docstrings; they are strict-mandatory when I teach python : )

**Comment by wking** [comment] 2016-02-10 19:44
On Wed, Feb 10, 2016 at 11:39:58AM -0800, Bill Mills wrote:
> That's ok - when I teach this material, 'close guidance' for error messages ==
> 
>  - Look at the first error and only the first error
>  - Look at the last line and only the last line of the error (*advanced students*: find the line number of the problem in the error body, too).
>  - Try and guess what that last line means from semantics.
>  - Remind them that this is hard and it's ok if it looks like gibberish (because it mostly is).

You forgot the obvious response to “hmm, this is hard”, which is
pasting that last line into your favorite search engine ;).  Usually
if you're having problems understanding it, a bunch of other people
have too, and some fraction of them have written nice blog posts and
SO entries unpacking it for you.

**Comment by BillMills** [comment] 2016-02-10 20:22
@wking this was my first reaction, too - to disastrous results! Beginners *hate* being told to google things - I think it makes them feel like their problems are trivial, and then when they encounter the stack post, that is often just as confusing (with an added dose of stack smarm). I would definitely do this with a more confident student, but for people already stressed out about debugging, this is more of a minefield than I anticipated at first. Again, still a good idea and still worth teaching; my top-line point here is we have to be super careful about framing here; perhaps by definition, a student in this situation is a-priori primed to feel frustrated.

**Comment by wking** [comment] 2016-02-10 20:37
On Wed, Feb 10, 2016 at 12:22:07PM -0800, Bill Mills wrote:
> … I think it makes them feel like their problems are trivial…

Huh, I wonder where that comes from.  Does pointing out that:

* Tracebacks and errors are fairly unique identifiers (so they're a
  good thing to search, if you want to search something).
* If you find anything, other folks were confused enough to bother
  with a blog or SO post, so it's probably not trivial.

help avoid that reaction?

> … and then when they encounter the stack post, that is often just as
> confusing (with an added dose of stack smarm)… we have to be super
> careful about framing here; perhaps by definition, a student in this
> situation is a-priori primed to feel frustrated.

Yeah, which is why having a mentor there to coach you through the
issue is nice (otherwise SWC would be a “read the lessons yourself”
course).  “Ask someone you know for advice” can get you that
pitched-for-you feedback, and that would be a good approach where
possible.  But not everyone has that sort of support system available,
and sometimes banging your head into the wall (either on your own or
with the help of your search engine) is your only option for getting
through that particular barrier and/or motivating you to move in a
different direction.  It's not fun, but I don't know if it's avoidable
(and feeling your head break through the wall is nice :).

**Comment by BillMills** [comment] 2016-02-10 20:43
> * If you find anything, other folks were confused enough to bother with a blog or SO post, so it's probably not trivial.

Yes! Excellent, this is great framing and context - just what we need to include.

Re: coaching, this is definitely effective - how do we scale it to a room of 40? Especially given the 15 min allocated to this topic, it's going to be tough to not leave 40-nHelpers flailing. Perhaps a couple of cooked examples to generate errors that have reasonably accessible stack answers - this way, staff can coach whole groups at once.

**Comment by wking** [comment] 2016-02-10 21:02
On Wed, Feb 10, 2016 at 12:43:14PM -0800, Bill Mills wrote:
> Perhaps a couple of cooked examples to generate errors that have
> reasonably accessible stack answers - this way, staff can coach
> whole groups at once.

My coaching example in [1] was intended to be outside of the workshop.
In the workshop, you have helpers you can flag down for incidental
errors.  We introduce help(), etc., so that learners can get out of
holes one their own / after they've gone home.  And yeah, scaling
one-on-one help is hard (which is why we have help() and SO).

I'd suggest talking over your procedure [2] and demoing it (including
the search, if possible) the first time you hit a traceback or when
you get to the help() section, whichever comes first.  Then reinforce
it as it seems appropriate, either with the whole class or with
one-on-one helper/learner discussion.  It takes a lot longer to talk
someone through solving their own own problem than it does to solve
the problem for them, and which course is more appropriate depends on
the time available, the centrality of the problem, and the
accessibility of solutions.

[1]: https://github.com/swcarpentry/python-novice-gapminder/issues/22#issuecomment-182573516
[2]: https://github.com/swcarpentry/python-novice-gapminder/issues/22#issuecomment-182544493

**Comment by gvwilson** [comment] 2016-07-25 17:55
Partly addressed by fc3103f, and partly addressed by content in `_episodes/05-error-messages.md`.  We should revisit once material is reorganized.

**Closed by gvwilson** 2016-07-25 17:55 UTC
