### ISSUE TITLE
Adding Anaconda to path

### ISSUE THREAD

**Issue by CallumWalley** [swcarpentry/python-novice-gapminder#434] opened 2019-08-08 21:16 UTC
Under "Running and Quitting > Getting Started with JupyterLab > [Windows Users](http://swcarpentry.github.io/python-novice-gapminder/01-run-quit/index.html#windows-users)"  it says you can launch jupyter lab through cmd. 

This didn't work for me until I added Anaconda to path.

In the [setup](http://swcarpentry.github.io/python-novice-gapminder/setup/) section is says:
`Double-click the executable and install Python 3 using MOST of the default settings. The only exception is to check the Make Anaconda the default Python option.`

![image](https://user-images.githubusercontent.com/35017184/62738150-ba44d280-ba85-11e9-8a56-4bc7c04ab227.png)

So:

a) Tick the 'add to path' box during anaconda install (in Setup page)
b) Open the anaconda shell rather than cmd. (Running and Quitting) 
c) I'm dumb and missing something.

**Comment by CallumWalley** [comment] 2019-08-12 02:10
Just to add, this hit all the Windows users in our workshop today.

**Comment by alee** [comment] 2019-08-12 06:26
Thanks for letting us know, @CallumWalley !

I'll look into this and see if I can reproduce it when I have access to a Windows machine tomorrow at work, I assume we should change the cmd shell to either open up the Anaconda shell or add Anaconda to PATH (which is probably less desirable if Anaconda itself is recommending that you *not* do that).

Was this on Windows 10 + the latest Anaconda (2019.7)?

**Comment by souravsingh** [comment] 2019-08-12 08:11
I have used Anaconda in Windows and have found that Anaconda to PATH was the best solution for me(even though Anaconda discourages it). Adding Anaconda to PATH allowed me to use Anaconda commands directly from Command prompt.

I would say adding Anaconda to PATH is same as adding Anaconda to `.bashrc`.

**Comment by vahtras** [comment] 2019-08-12 08:38
I have done this myself, and it works. However, I consider it to be a last
solution which may have unknown consequences, which is probably why
Anaconda discourages it. I would hesitate to have it as a general
recommendation for a workshop.

**Comment by souravsingh** [comment] 2019-08-12 08:56
I believe that if you are using the softwares provided by Anaconda and do not have any existing installation of Python or R(which is the case with me), adding Anaconda to PATH should be fine and have no problems. 

On the other hand, If you have some existing installation of Python on the system on which some of your packages and scripts are dependent on, I would discourage adding Anaconda to PATH and instead tell users to use Anaconda prompt.

Maybe telling users to use Anaconda prompt should be a safe bet, since many users have other scientific softwares preinstalled.

**Comment by CallumWalley** [comment] 2019-08-13 03:37
Something like

### Windows Users
To start the JupyterLab server you will need to open 'Anaconda Prompt', then type the command:

~~~
$ jupyter lab
~~~
{: .bash}

<hr>

By the way, what is the etiquette regarding code blocks that don't have a css class? Just go with `.bash` as in example?

**Comment by alee** [comment] 2019-08-13 06:58
That sounds good to me, would you be willing to submit a PR to address this? We're happy to guide you through the contribution process.

I think the `.bash` css class  is fine, though the styles maintainers @fmichonneau and @maxim-belkin may have more opinions on this..

**Comment by maxim-belkin** [comment] 2019-08-13 19:23
both `{: .bash}` and `{: .language-bash}` exist but majority of lessons use `{: .language-bash}`

**Comment by alee** [comment] 2019-08-19 23:54
fixed in #435

**Closed by alee** 2019-08-19 23:54 UTC
