### ISSUE TITLE
Start times on schedule page at 00:00 for consistency with other lessons

### ISSUE THREAD

**Issue by kschwenzfeier** [swcarpentry/python-novice-gapminder#575] opened 2021-11-09 10:10 UTC
<details>
<summary><strong>Improve consistency on scheduling page with other core lessons</strong></summary>
Both python lessons within core curriculum show an example schedule starting at 9:00 while all other lessons start at 0:00. 
I suggest to shift the start to 0:00 as well as it is easier to plan with a "time spent" kind of timescale than a fixed "this lesson starts in the morning and if it doesn't, there will be math involved." 
</details>

**Comment by vahtras** [comment] 2021-11-09 10:54
That makes sense to me

**Comment by alee** [comment] 2021-11-17 05:51
This is essentially a duplicate of #571 and will be fixed soon by adjusting https://github.com/swcarpentry/python-novice-gapminder/blob/81690d2c5794a89b287bbc834a1c3a9a74201967/_config.yml#L63

Thanks for bringing it up!

**Closed by alee** 2021-11-17 05:51 UTC
Labels: help wanted, good first issue
